### ISSUE TITLE
use with apache and hosting support

### ISSUE THREAD

**Issue by fredrich** [DiamondMVC/Diamond#83]
is there doc to use diamond mvc with apache

and to be used on shared hosting envieonment on linux, in other words the setting options of resource  limitation (io, memory, thread, cpu, process). that kind of stuff. thanks.

**Comment by bausshf** [comment]
Hi @fredrich,

Currently there are documentation for deploying with nginx, heroku and microsoft azure only.

If I can find the time for it, I might see if I can write something up for apache and/or shared hosting environments, but it shouldn't be much different from any other deployments.

**Comment by Giancarlos** [comment]
I know this question is a bit old but for anyone wondering the same or similar:

You would not want to do it on a shared host (that type of hosting environment is not **truly** designed for this type of project). You need a VPS or Dedicated server, or something that will let you run an executable.

Once you have the appropriate hosting environment, then you can setup Apache to be a reverse proxy for the application, though I suggest nginx instead since you already have a guide from the maintainers for use with nginx.

On the note of hosting: I also recommend either Microsoft Azure or DigitalOcean (or similar) though Azure might have something easier. It could also be deployed in a Docker container or similar I'm sure though I've never done that, mentioning for those who might be more familiar with container solutions as well, I know some hosting companies have services for deploying containers.

**Comment by bausshf** [comment]
@Giancarlos - I agree with what you've said and I think it's best to just close this issue.

I would really recommend to use another environment other than shared hosting.

Either run it on a dedicated server / VPS that has Linux or Windows and then you can install Nginx or Apache and setup reverse proxies to the project.

The other alternative would be something "cloud-based" like Microsoft Azure, Amazon Web Services or Heroku.

Currently there are no tutorials for anything other than Nginx, Microsoft Azure and Heroku, _but_ it should be pretty straight forward with each platform and environment.

If it's not absolutely important to use shared hosting, then I'll not look into writing a guide and testing.

**Comment by bausshf** [comment]
Closing this.
